source 'https://rubygems.org'

if RUBY_VERSION >= '2.4'
  # Pin all versions
  gem 'tilt', '2.0.10'
  gem 'erubi', '1.10.0'
  gem 'haml', '5.2.2'
  gem 'roda', '3.54.0'
  gem 'rodauth', '2.21.0'
  gem 'bcrypt', '3.1.17'
  gem 'refrigerator', '1.4.1'
  gem 'bigdecimal', '3.1.5'
  gem 'sequel', '5.54.0'
  if RUBY_ENGINE == 'jruby'
    gem 'activerecord-jdbcsqlite3-adapter', '~> 51.0'
  else
    gem 'sqlite3', '1.4.2'
  end
  gem 'rake', '13.0.6'
  gem 'puma', '5.6.2'
  gem 'nio4r', '2.5.8'
  gem 'rack', '2.2.3'

  gem 'mail', '2.7.1'
  if RUBY_VERSION >= '3.1.0'
    gem 'net-smtp', '0.3.1'
    gem 'net-imap', '0.2.3'
    gem 'net-pop', '0.1.1'

    # rake gem dependency on Ruby 3.1+
    gem 'matrix', '0.4.2'
  end
  if RUBY_VERSION >= '3.4.0'
    gem 'base64'
    gem 'digest', '~> 3.1.1'
  end
else
  gem 'tilt'
  gem 'erubi'
  gem 'haml'
  gem 'roda'
  gem 'rodauth'
  gem 'bcrypt'
  gem 'refrigerator'
  gem 'sequel'
  gem 'sqlite3'
  gem 'rake'
  gem 'puma', '3.11.4'
  gem 'nio4r'
  gem 'rack'
  gem 'mail'
end
